import jsPDF from 'jspdf'

const COLORS = {
  brand:   [9, 58, 122],
  blue:    [5, 114, 178],
  teal:    [11, 181, 146],
  pink:    [245, 84, 134],
  amber:   [217, 119, 6],
  slate900:[15, 23, 42],
  slate700:[51, 65, 85],
  slate500:[100, 116, 139],
  slate400:[148, 163, 184],
  slate200:[226, 232, 240],
  slate100:[241, 245, 249],
  slate50: [248, 250, 252],
  white:   [255, 255, 255],
}

const setFill = (doc, c) => doc.setFillColor(c[0], c[1], c[2])
const setText = (doc, c) => doc.setTextColor(c[0], c[1], c[2])
const setDraw = (doc, c) => doc.setDrawColor(c[0], c[1], c[2])

function drawHeader(doc, report) {
  // Top brand band
  setFill(doc, COLORS.brand)
  doc.rect(0, 0, 210, 30, 'F')

  // Accent stripe
  setFill(doc, COLORS.teal)
  doc.rect(0, 30, 210, 1.4, 'F')

  // Logo dot + wordmark
  setFill(doc, COLORS.teal)
  doc.circle(18, 15, 4, 'F')
  setFill(doc, COLORS.white)
  doc.circle(18, 15, 1.5, 'F')

  setText(doc, COLORS.white)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text('BRECAI-FED', 27, 14)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.text('Federated AI · Breast Cancer Molecular Subtyping', 27, 19)

  // Right side meta
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.text('CLINICAL REPORT', 192, 13, { align: 'right' })
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.text(report.id, 192, 18, { align: 'right' })
  doc.text(report.date, 192, 22.5, { align: 'right' })
}

function drawFooter(doc, pageNum, pageCount) {
  setDraw(doc, COLORS.slate200)
  doc.setLineWidth(0.2)
  doc.line(15, 282, 195, 282)
  setText(doc, COLORS.slate400)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.text('CONFIDENTIAL · HIPAA-compliant · For licensed clinicians only', 15, 287)
  doc.text(`Page ${pageNum} / ${pageCount}`, 195, 287, { align: 'right' })
  doc.setFontSize(6.5)
  setText(doc, COLORS.slate500)
  doc.text('Generated by BRECAI-FED v3.2 · Federated Round 8', 15, 291)
  doc.text(`Hash: ${hashId(`${pageNum}${Date.now()}`).slice(0, 12).toUpperCase()}`, 195, 291, { align: 'right' })
}

function hashId(s) {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) >>> 0
  return h.toString(16)
}

function sectionTitle(doc, y, label) {
  setFill(doc, COLORS.slate50)
  doc.roundedRect(15, y, 180, 7, 1.2, 1.2, 'F')
  setFill(doc, COLORS.brand)
  doc.rect(15, y, 1.4, 7, 'F')
  setText(doc, COLORS.brand)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.text(label.toUpperCase(), 19, y + 4.7)
  return y + 11
}

function kvRow(doc, x, y, label, value, w = 60) {
  setText(doc, COLORS.slate400)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(6.5)
  doc.text(label.toUpperCase(), x, y)
  setText(doc, COLORS.slate900)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9.5)
  doc.text(String(value ?? '—'), x, y + 5)
}

function pillBadge(doc, x, y, text, color) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  const w = doc.getTextWidth(text) + 6
  setFill(doc, color)
  doc.roundedRect(x, y - 4, w, 5.5, 2.75, 2.75, 'F')
  setText(doc, COLORS.white)
  doc.text(text, x + 3, y)
  return x + w + 2
}

function progressBar(doc, x, y, w, value, color) {
  setFill(doc, COLORS.slate100)
  doc.roundedRect(x, y, w, 2, 1, 1, 'F')
  const fillW = Math.max(0.5, (Math.min(100, Math.max(0, value)) / 100) * w)
  setFill(doc, color)
  doc.roundedRect(x, y, fillW, 2, 1, 1, 'F')
}

function colorForResult(result) {
  return result === 'Luminal A' ? COLORS.teal : COLORS.pink
}

function therapyRecommendation(report) {
  if (report.result === 'Luminal A') {
    return [
      'Hormonal (endocrine) therapy: Tamoxifen or aromatase inhibitor (5-10 years).',
      'Consider surgical lumpectomy with adjuvant radiotherapy.',
      'Routine 6-month follow-up; annual MRI for the first 2 years.',
    ]
  }
  return [
    'Multidisciplinary tumor board (MDT) review recommended.',
    'Consider neoadjuvant chemotherapy regimen (anthracycline + taxane).',
    'HER2-targeted therapy (e.g., Trastuzumab) if HER2+ confirmed by IHC/FISH.',
    '3-month follow-up with restaging imaging.',
  ]
}

export function generateReportPDF(report, patient = null) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  drawHeader(doc, report)

  // ── Title block ───────────────────────────────────────────────────────────
  let y = 42
  setText(doc, COLORS.slate900)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text(report.type, 15, y)
  y += 6
  setText(doc, COLORS.slate500)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`Patient: ${report.patient}  ·  Reporting clinician: ${report.doctor}`, 15, y)
  y += 4

  // status pills
  y += 4
  let px = 15
  px = pillBadge(doc, px, y, report.status === 'signed' ? 'SIGNED' : 'DRAFT', report.status === 'signed' ? COLORS.teal : COLORS.amber)
  px = pillBadge(doc, px, y, report.result.toUpperCase(), colorForResult(report.result))
  px = pillBadge(doc, px, y, `${Number(report.prob).toFixed(1)}% CONFIDENCE`, COLORS.blue)
  if (patient?.risk) px = pillBadge(doc, px, y, `${String(patient.risk).toUpperCase()} RISK`,
    patient.risk === 'high' ? COLORS.pink : patient.risk === 'medium' ? COLORS.amber : COLORS.teal)

  y += 6

  // ── Patient summary ───────────────────────────────────────────────────────
  y = sectionTitle(doc, y, 'Patient Summary')
  setDraw(doc, COLORS.slate200)
  doc.setLineWidth(0.2)
  doc.roundedRect(15, y - 2, 180, 28, 2, 2)
  const cols = [
    ['Patient ID', report.patientId || '—'],
    ['Age', patient?.age != null ? `${patient.age} y` : '—'],
    ['DOB', patient?.dob || '—'],
    ['Federated Site', patient?.site ? `Site ${patient.site}` : '—'],
    ['Tumor Size', patient?.tumorSize != null ? `${patient.tumorSize} mm` : '—'],
    ['Lymph Node', patient?.lymphSite || '—'],
    ['Report Date', report.date],
    ['Risk Level', patient?.risk ? String(patient.risk).toUpperCase() : '—'],
  ]
  cols.forEach((c, i) => {
    const cx = 19 + (i % 4) * 44
    const cy = y + 4 + Math.floor(i / 4) * 12
    kvRow(doc, cx, cy, c[0], c[1])
  })
  y += 32

  // ── AI Subtype Verdict ────────────────────────────────────────────────────
  y = sectionTitle(doc, y, 'AI Subtype Verdict')
  setDraw(doc, COLORS.slate200)
  doc.roundedRect(15, y - 2, 180, 30, 2, 2)
  setText(doc, COLORS.slate400)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7)
  doc.text('PREDICTED MOLECULAR SUBTYPE', 19, y + 3)
  setText(doc, colorForResult(report.result))
  doc.setFont('helvetica', 'bold'); doc.setFontSize(20)
  doc.text(report.result, 19, y + 13)

  setText(doc, COLORS.slate400)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7)
  doc.text('CONFIDENCE SCORE', 19, y + 19)
  setText(doc, COLORS.slate900)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(11)
  doc.text(`${Number(report.prob).toFixed(1)}%`, 19, y + 25)
  progressBar(doc, 40, y + 23, 60, Number(report.prob) || 0, colorForResult(report.result))

  // model badge on the right
  setText(doc, COLORS.slate400)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(7)
  doc.text('MODEL', 130, y + 3)
  setText(doc, COLORS.slate900)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9)
  doc.text('brecai-v3.2', 130, y + 9)
  setText(doc, COLORS.slate500)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8)
  doc.text('Federated round 8', 130, y + 14)
  doc.text('3 sites · 141 cases trained', 130, y + 19)

  y += 35

  // ── Biomarker panel ───────────────────────────────────────────────────────
  if (patient) {
    y = sectionTitle(doc, y, 'Biomarker Panel')
    const bios = [
      { label: 'ER',    val: patient.er,   max: 100, good: patient.er >= 50,    unit: '%' },
      { label: 'PR',    val: patient.pr,   max: 100, good: patient.pr >= 20,    unit: '%' },
      { label: 'Ki-67', val: patient.ki67, max: 100, good: (patient.ki67 ?? 0) < 20, unit: '%' },
      { label: 'HER2',  val: patient.her2, isText: true, good: patient.her2 === 'Negative' },
    ]
    setDraw(doc, COLORS.slate200)
    bios.forEach((b, i) => {
      const x = 15 + i * 45
      doc.roundedRect(x, y - 2, 42, 22, 2, 2)
      setText(doc, COLORS.slate400)
      doc.setFont('helvetica', 'bold'); doc.setFontSize(6.5)
      doc.text(b.label.toUpperCase(), x + 3, y + 2)
      const c = b.good ? COLORS.teal : COLORS.pink
      setText(doc, c)
      doc.setFont('helvetica', 'bold'); doc.setFontSize(13)
      doc.text(b.isText ? String(b.val ?? '—') : `${b.val ?? 0}${b.unit || ''}`, x + 3, y + 10)
      if (!b.isText) progressBar(doc, x + 3, y + 14, 36, Number(b.val) || 0, c)
    })
    y += 26
  }

  // ── Feature attribution ───────────────────────────────────────────────────
  y = sectionTitle(doc, y, 'Feature Attribution (SHAP)')
  setDraw(doc, COLORS.slate200)
  doc.roundedRect(15, y - 2, 180, 36, 2, 2)
  const features = [
    { name: 'ER Expression',    val: patient?.er ?? 80,   sign: '+' },
    { name: 'PR Expression',    val: patient?.pr ?? 70,   sign: '+' },
    { name: 'Ki-67 Index',      val: patient?.ki67 ?? 25, sign: '-' },
    { name: 'Tumor Size',       val: Math.min(100, (patient?.tumorSize ?? 22) * 2), sign: '~' },
  ]
  features.forEach((f, i) => {
    const fy = y + 3 + i * 7.5
    setText(doc, COLORS.slate700)
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8)
    doc.text(f.name, 19, fy + 3)
    progressBar(doc, 80, fy + 1.5, 80, f.val, f.sign === '-' ? COLORS.pink : COLORS.blue)
    setText(doc, COLORS.slate900)
    doc.setFont('helvetica', 'bold'); doc.setFontSize(8)
    doc.text(`${f.sign}${(f.val / 100).toFixed(2)}`, 188, fy + 3, { align: 'right' })
  })
  y += 40

  // ── Therapy Recommendation ────────────────────────────────────────────────
  y = sectionTitle(doc, y, 'Therapy Recommendation')
  setDraw(doc, COLORS.slate200)
  const recs = therapyRecommendation(report)
  const recsHeight = 6 + recs.length * 5.5
  doc.roundedRect(15, y - 2, 180, recsHeight, 2, 2)
  setText(doc, COLORS.slate700)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
  recs.forEach((r, i) => {
    setFill(doc, colorForResult(report.result))
    doc.circle(20, y + 3 + i * 5.5, 0.9, 'F')
    doc.text(r, 23, y + 4 + i * 5.5)
  })
  y += recsHeight + 4

  // ── Clinical Notes ────────────────────────────────────────────────────────
  if (report.notes) {
    y = sectionTitle(doc, y, 'Clinical Notes')
    setDraw(doc, COLORS.slate200)
    const lines = doc.splitTextToSize(report.notes, 174)
    const notesH = Math.max(12, lines.length * 4.4 + 6)
    doc.roundedRect(15, y - 2, 180, notesH, 2, 2)
    setText(doc, COLORS.slate700)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
    doc.text(lines, 19, y + 4)
    y += notesH + 4
  }

  // ── Signature block ───────────────────────────────────────────────────────
  if (y > 240) { doc.addPage(); drawHeader(doc, report); y = 42 }
  setDraw(doc, COLORS.slate200)
  doc.roundedRect(15, y, 180, 28, 2, 2)
  setText(doc, COLORS.slate400)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(6.5)
  doc.text('REPORTING CLINICIAN', 19, y + 5)
  setText(doc, COLORS.slate900)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(11)
  doc.text(report.doctor, 19, y + 12)
  setText(doc, COLORS.slate500)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8)
  doc.text(`Signed: ${report.status === 'signed' ? report.date : '— DRAFT —'}`, 19, y + 17)

  setText(doc, COLORS.slate400)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(6.5)
  doc.text('SIGNATURE', 130, y + 5)
  setDraw(doc, COLORS.slate400)
  doc.setLineWidth(0.4)
  doc.line(130, y + 22, 188, y + 22)
  if (report.status === 'signed') {
    setText(doc, COLORS.brand)
    doc.setFont('times', 'italic'); doc.setFontSize(16)
    doc.text(report.doctor.split(' ').slice(-1)[0] || 'Benali', 134, y + 19)
  }

  // Footer + page numbers
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    drawFooter(doc, i, pageCount)
  }

  return doc
}

export function downloadReportPDF(report, patient = null) {
  const doc = generateReportPDF(report, patient)
  doc.save(`${report.id}_${(report.patient || 'patient').replace(/\W+/g, '_')}.pdf`)
}

export function previewReportPDF(report, patient = null) {
  const doc = generateReportPDF(report, patient)
  return doc.output('bloburl')
}
