import { useState, useEffect, useCallback } from 'react'
import { motion } from 'framer-motion'
import { FileText, Eye, CheckCircle2, Clock, Edit3 } from 'lucide-react'
import { LabHero, SparkTile, DataTable, StatusPill, Avatar } from '@/components/admin'
import { Btn, Modal, stagger } from '@/components/shared'
import orgManager from '@/api/api-client/orgManager'

const REPORT_STATUS_TONE  = { draft: 'slate', finalized: 'teal', pending: 'amber' }
const REPORT_STATUS_LABEL = { draft: 'Draft', finalized: 'Finalized', pending: 'Pending' }

export default function OrgReports() {
  const [reports, setReports] = useState([])
  const [meta, setMeta] = useState({ current_page: 1, last_page: 1, total: 0 })
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(true)
  const [viewing, setViewing] = useState(null)

  const load = useCallback(async (p = 1) => {
    setLoading(true)
    try {
      const res = await orgManager.reports.list({ page: p })
      setReports(res.data ?? [])
      setMeta({ current_page: res.current_page ?? 1, last_page: res.last_page ?? 1, total: res.total ?? 0 })
    } catch {
      // silently fail
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { load(page) }, [load, page])

  const stats = {
    total:     meta.total,
    finalized: reports.filter(r => r.status === 'finalized').length,
    draft:     reports.filter(r => r.status === 'draft').length,
  }

  const columns = [
    {
      key: 'id', label: 'Report', sortable: true,
      render: (r) => (
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-[#0BB592] to-[#047857] text-white font-black flex items-center justify-center text-xs shadow-sm shrink-0">
            <FileText className="w-4 h-4" />
          </div>
          <div>
            <p className="font-extrabold text-slate-900 text-sm">Report #{r.id}</p>
            <p className="text-[11px] font-semibold text-slate-500">
              {r.examination_id ? `Exam #${r.examination_id}` : '—'}
            </p>
          </div>
        </div>
      ),
    },
    {
      key: 'doctor', label: 'Doctor', sortable: true,
      render: (r) => r.doctor ? (
        <div className="flex items-center gap-2">
          <Avatar name={r.doctor.name} size="sm" />
          <span className="text-xs font-bold text-slate-700">{r.doctor.name}</span>
        </div>
      ) : <span className="text-slate-400 text-xs">—</span>,
    },
    {
      key: 'status', label: 'Status', sortable: true,
      render: (r) => {
        const tone  = REPORT_STATUS_TONE[r.status]  || 'slate'
        const label = REPORT_STATUS_LABEL[r.status] || r.status
        const Icon  = r.status === 'finalized' ? CheckCircle2 : r.status === 'draft' ? Edit3 : Clock
        return <StatusPill tone={tone}><Icon className="w-3 h-3" /> {label}</StatusPill>
      },
    },
    {
      key: 'patient_id', label: 'Patient', sortable: true,
      render: (r) => <span className="font-mono text-xs font-bold text-slate-600">{r.patient?.patient_identifier || (r.patient_id ? `#${r.patient_id}` : '—')}</span>,
    },
    {
      key: 'finalized_at', label: 'Finalized', sortable: true,
      render: (r) => <span className="font-mono text-[11px] font-semibold text-slate-500">{r.finalized_at ? new Date(r.finalized_at).toLocaleDateString() : '—'}</span>,
    },
    {
      key: 'created_at', label: 'Created', sortable: true,
      render: (r) => <span className="font-mono text-[11px] font-semibold text-slate-500">{r.created_at ? new Date(r.created_at).toLocaleDateString() : '—'}</span>,
    },
    {
      key: '_actions', label: '', align: 'right',
      render: (r) => (
        <button onClick={(e) => { e.stopPropagation(); setViewing(r) }}
          className="w-8 h-8 rounded-lg border border-slate-200 flex items-center justify-center text-slate-400 hover:text-[#0BB592] hover:border-[#0BB592] transition">
          <Eye className="w-3.5 h-3.5" />
        </button>
      ),
    },
  ]

  return (
    <motion.div variants={stagger} initial="hidden" animate="show">
      <LabHero
        eyebrow="Clinical Data · Read Only"
        title="Reports"
        subtitle="View all clinical reports generated by your organization's doctors. Read-only access for site admins."
        icon={FileText}
        stats={[
          { label: 'Total',     value: meta.total,      sub: 'All reports'  },
          { label: 'Finalized', value: stats.finalized, sub: 'Completed'    },
          { label: 'Draft',     value: stats.draft,     sub: 'In progress'  },
        ]}
      />

      <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
        <SparkTile label="Total reports" value={meta.total}      sub="All time"    icon={FileText}    color="teal"  trend={[2,3,4,5,6,7,8,9,10]} />
        <SparkTile label="Finalized"     value={stats.finalized} sub="Completed"   icon={CheckCircle2} color="blue"  trend={[1,2,2,3,4,5,5,6,7]} />
        <SparkTile label="Draft"         value={stats.draft}     sub="In progress" icon={Edit3}        color="amber" trend={[1,1,1,2,2,2,2,2,2]} />
      </div>

      {loading ? (
        <div className="bg-white rounded-2xl border border-slate-200 p-12 flex justify-center">
          <div className="w-8 h-8 rounded-full border-4 border-slate-200 border-t-[#0BB592] animate-spin" />
        </div>
      ) : (
        <DataTable
          columns={columns}
          rows={reports}
          searchKeys={[]}
          filters={[
            { key: 'status', label: 'status', options: [
              { value: 'finalized', label: 'Finalized' },
              { value: 'draft',     label: 'Draft'     },
            ]},
          ]}
          emptyMessage="No reports found."
          onRowClick={(r) => setViewing(r)}
        />
      )}

      {meta.last_page > 1 && (
        <div className="flex items-center justify-center gap-2 mt-4">
          <Btn variant="secondary" onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1}>Previous</Btn>
          <span className="text-xs font-bold text-slate-500">Page {meta.current_page} of {meta.last_page}</span>
          <Btn variant="secondary" onClick={() => setPage(p => Math.min(meta.last_page, p + 1))} disabled={page === meta.last_page}>Next</Btn>
        </div>
      )}

      {/* Report detail modal */}
      <Modal
        open={!!viewing}
        onClose={() => setViewing(null)}
        title={`Report #${viewing?.id}`}
        subtitle={`Status: ${REPORT_STATUS_LABEL[viewing?.status] || viewing?.status || '—'}`}
        size="md"
        footer={<Btn variant="secondary" onClick={() => setViewing(null)}>Close</Btn>}
      >
        {viewing && (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-3">
              {[
                { label: 'Doctor',      value: viewing.doctor?.name },
                { label: 'Patient',     value: viewing.patient?.patient_identifier || (viewing.patient_id ? `#${viewing.patient_id}` : null) },
                { label: 'Examination', value: viewing.examination_id ? `#${viewing.examination_id}` : null },
                { label: 'Status',      value: REPORT_STATUS_LABEL[viewing.status] || viewing.status },
                { label: 'Created',     value: viewing.created_at ? new Date(viewing.created_at).toLocaleDateString() : null },
                { label: 'Finalized',   value: viewing.finalized_at ? new Date(viewing.finalized_at).toLocaleDateString() : null },
              ].map(f => (
                <div key={f.label} className="rounded-xl bg-slate-50 border border-slate-100 px-3 py-2.5">
                  <p className="text-[9px] font-black uppercase tracking-widest text-slate-400">{f.label}</p>
                  <p className="text-sm font-bold text-slate-900 mt-0.5">{f.value ?? '—'}</p>
                </div>
              ))}
            </div>
            {viewing.summary && (
              <div className="rounded-xl bg-slate-50 border border-slate-100 px-4 py-3">
                <p className="text-[9px] font-black uppercase tracking-widest text-slate-400 mb-1.5">Summary</p>
                <p className="text-sm text-slate-700 leading-relaxed">{viewing.summary}</p>
              </div>
            )}
            {viewing.doctor_conclusion && (
              <div className="rounded-xl bg-teal-50 border border-teal-100 px-4 py-3">
                <p className="text-[9px] font-black uppercase tracking-widest text-teal-500 mb-1.5">Doctor Conclusion</p>
                <p className="text-sm text-slate-700 leading-relaxed">{viewing.doctor_conclusion}</p>
              </div>
            )}
          </div>
        )}
      </Modal>
    </motion.div>
  )
}
